# (generated with --quick)

import skolemizer.skolemizer
from typing import Type

Skolemizer: Type[skolemizer.skolemizer.Skolemizer]
os: module

def test_add_skolemization() -> None: ...
def test_get_baseurl() -> None: ...
def test_get_baseurl_missing_slash_at_end() -> None: ...
def test_get_baseurl_not_valid_url() -> None: ...
def test_has_skolemization_morfologi_invalid_url() -> None: ...
